import { Kumbh_Sans } from 'next/font/google';

import '@/assets/styles/globals.css';
import Footer from '@/components/footer/footer.comp';
import Header from '@/components/header/header.comp';

const kumbh = Kumbh_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${kumbh.className} bg-gray-100`}>
        <div className='min-h-screen flex flex-col justify-between'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
